package org.propagate.common.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.propagate.common.domain.rollout.Nullable;

import java.io.Serializable;
import java.util.*;

@JsonIgnoreProperties(ignoreUnknown = true)
public class FeatureFlag implements Serializable {
    @Nullable
    private String id;
    /**
     * Every feature flag is uniquely identified by its key
     */
    private String key;

    private String name;

    private String description;

    private FeatureFlagType type;

    private List<Variation> variations;
    
    private List<RolloutRules> rolloutRules;

    private boolean archived = false;

    private boolean targeting = false;

    @Nullable
    private Date created;

    @Nullable
    private Date lastUpdated;

// region Constructor, getters, setters, equals, hashCode, toString, builder -- generated by BoB the Builder of Beans

// The code below has been generated by BoB the Builder of Beans based on the class' fields.
// Everything after this comment will be regenerated if you invoke BoB again.
// If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    @Deprecated
    public FeatureFlag() {
    }

    protected FeatureFlag(String id, String key, String name, String description, FeatureFlagType type, List<Variation> variations, List<RolloutRules> rolloutRules, boolean archived, boolean targeting, Date created, Date lastUpdated) {
        this.id = id;
        this.key = key;
        this.name = name;
        this.description = description;
        this.type = type;
        this.variations = variations != null ? new ArrayList<>(variations) : null;
        this.rolloutRules = rolloutRules != null ? new ArrayList<>(rolloutRules) : null;
        this.archived = archived;
        this.targeting = targeting;
        this.created = created;
        this.lastUpdated = lastUpdated;
    }

// region Getters and setters -- generated by BoB the Builder of Beans

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public FeatureFlagType getType() {
        return type;
    }

    public void setType(FeatureFlagType type) {
        this.type = type;
    }

    public List<Variation> getVariations() {
        return variations;
    }

    public void setVariations(List<Variation> variations) {
        this.variations = variations != null ? new ArrayList<>(variations) : null;
    }

    public List<RolloutRules> getRolloutRules() {
        return rolloutRules;
    }

    public void setRolloutRules(List<RolloutRules> rolloutRules) {
        this.rolloutRules = rolloutRules != null ? new ArrayList<>(rolloutRules) : null;
    }

    public boolean isArchived() {
        return archived;
    }

    public void setArchived(boolean archived) {
        this.archived = archived;
    }

    public boolean isTargeting() {
        return targeting;
    }

    public void setTargeting(boolean targeting) {
        this.targeting = targeting;
    }

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }// endregion Getters and setters

// region hashCode() and equals() -- generated by BoB the Builder of Beans

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        FeatureFlag that = (FeatureFlag) o;

        return Objects.equals(this.getId(), that.getId()) && Objects.equals(this.getKey(), that.getKey()) && Objects.equals(this.getName(), that.getName()) && Objects.equals(this.getDescription(), that.getDescription()) && Objects.equals(this.getType(), that.getType()) && Objects.equals(this.getVariations(), that.getVariations()) && Objects.equals(this.getRolloutRules(), that.getRolloutRules()) && Objects.equals(this.isArchived(), that.isArchived()) && Objects.equals(this.isTargeting(), that.isTargeting()) && Objects.equals(this.getCreated(), that.getCreated()) && Objects.equals(this.getLastUpdated(), that.getLastUpdated());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getKey(), getName(), getDescription(), getType(), getVariations(), getRolloutRules(), isArchived(), isTargeting(), getCreated(), getLastUpdated());
    }// endregion hashCode() and equals()

// region toString() -- generated by BoB the Builder of Beans

    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("id=" + getId())
                .add("key=" + getKey())
                .add("name=" + getName())
                .add("description=" + getDescription())
                .add("type=" + getType())
                .add("variations=" + getVariations())
                .add("rolloutRules=" + getRolloutRules())
                .add("archived=" + isArchived())
                .add("targeting=" + isTargeting())
                .add("created=" + getCreated())
                .add("lastUpdated=" + getLastUpdated())
                .toString();
    }// endregion toString()

// region Builder -- generated by BoB the Builder of Beans

    public static FeatureFlag.Builder builder() {
        return new FeatureFlag.Builder();
    }

    public static FeatureFlag.Builder builder(FeatureFlag data) {
        return new FeatureFlag.Builder(data);
    }

    public static final class Builder {

        private String id;
        private String key;
        private String name;
        private String description;
        private FeatureFlagType type;
        private List<Variation> variations;
        private List<RolloutRules> rolloutRules;
        private boolean archived;
        private boolean targeting;
        private Date created;
        private Date lastUpdated;

        private Builder() {
        }

        private Builder(FeatureFlag initialData) {
            this.id = initialData.id;
            this.key = initialData.key;
            this.name = initialData.name;
            this.description = initialData.description;
            this.type = initialData.type;
            this.variations = initialData.variations != null ? new ArrayList<>(initialData.variations) : null;
            this.rolloutRules = initialData.rolloutRules != null ? new ArrayList<>(initialData.rolloutRules) : null;
            this.archived = initialData.archived;
            this.targeting = initialData.targeting;
            this.created = initialData.created;
            this.lastUpdated = initialData.lastUpdated;
        }

        public Builder setId(String id) {
            this.id = id;
            return this;
        }

        public Builder setKey(String key) {
            this.key = key;
            return this;
        }

        public Builder setName(String name) {
            this.name = name;
            return this;
        }

        public Builder setDescription(String description) {
            this.description = description;
            return this;
        }

        public Builder setType(FeatureFlagType type) {
            this.type = type;
            return this;
        }

        public Builder setVariations(List<Variation> variations) {
            this.variations = variations;
            return this;
        }

        public Builder setRolloutRules(List<RolloutRules> rolloutRules) {
            this.rolloutRules = rolloutRules;
            return this;
        }

        public Builder setArchived(boolean archived) {
            this.archived = archived;
            return this;
        }

        public Builder setTargeting(boolean targeting) {
            this.targeting = targeting;
            return this;
        }

        public Builder setCreated(Date created) {
            this.created = created;
            return this;
        }

        public Builder setLastUpdated(Date lastUpdated) {
            this.lastUpdated = lastUpdated;
            return this;
        }

        public FeatureFlag build() {
            return new FeatureFlag(id, key, name, description, type, variations, rolloutRules, archived, targeting, created, lastUpdated);
        }
    }// endregion Builder
// endregion Constructor, getters, setters, equals, hashCode, toString, builder
}
