package org.propagate.common.domain;

import org.propagate.common.domain.rollout.Nullable;
import org.propagate.common.domain.rollout.RolloutRule;

import java.io.Serializable;
import java.util.*;

public class RolloutRules implements Serializable {
    @Nullable
    private Long id;
    private String namespace;
    private Variation defaultVariationTargetingOff;
    private Variation defaultVariationTargetingOn;
    private List<RolloutRule> rolloutRules;
    @Nullable
    private Date created;
    @Nullable
    private Date lastUpdated;

    // region Constructor, getters, setters, equals, hashCode, toString, builder -- generated by BoB the Builder of Beans
    // The code below has been generated by BoB the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke BoB again.
    // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    protected RolloutRules(@Nullable Long id, String namespace, Variation defaultVariationTargetingOff, Variation defaultVariationTargetingOn, Collection<RolloutRule> rolloutRules, @Nullable Date created, @Nullable Date lastUpdated) {
        this.id = id;
        this.namespace = Objects.requireNonNull(namespace);
        this.defaultVariationTargetingOff = Objects.requireNonNull(defaultVariationTargetingOff);
        this.defaultVariationTargetingOn = Objects.requireNonNull(defaultVariationTargetingOn);
        this.rolloutRules = new ArrayList<>(Objects.requireNonNull(rolloutRules));
        this.created = created;
        this.lastUpdated = lastUpdated;
    }

    // region Getters and setters -- generated by BoB the Builder of Beans
    public Optional<Long> getId() {
        return Optional.ofNullable(id);
    }

    public void setId(@Nullable Long id) {
        this.id = id;
    }

    public String getNamespace() {
        return namespace;
    }

    public void setNamespace(String namespace) {
        this.namespace = Objects.requireNonNull(namespace);
    }

    public Variation getDefaultVariationTargetingOff() {
        return defaultVariationTargetingOff;
    }

    public void setDefaultVariationTargetingOff(Variation defaultVariationTargetingOff) {
        this.defaultVariationTargetingOff = Objects.requireNonNull(defaultVariationTargetingOff);
    }

    public Variation getDefaultVariationTargetingOn() {
        return defaultVariationTargetingOn;
    }

    public void setDefaultVariationTargetingOn(Variation defaultVariationTargetingOn) {
        this.defaultVariationTargetingOn = Objects.requireNonNull(defaultVariationTargetingOn);
    }

    public List<RolloutRule> getRolloutRules() {
        return rolloutRules;
    }

    public void setRolloutRules(List<RolloutRule> rolloutRules) {
        this.rolloutRules = new ArrayList<>(Objects.requireNonNull(rolloutRules));
    }

    public Optional<Date> getCreated() {
        return Optional.ofNullable(created);
    }

    public void setCreated(@Nullable Date created) {
        this.created = created;
    }

    public Optional<Date> getLastUpdated() {
        return Optional.ofNullable(lastUpdated);
    }

    public void setLastUpdated(@Nullable Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }// endregion Getters and setters

    // region hashCode() and equals() -- generated by BoB the Builder of Beans
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        RolloutRules that = (RolloutRules) o;

        return Objects.equals(this.getId(), that.getId()) && Objects.equals(this.getNamespace(), that.getNamespace()) && Objects.equals(this.getDefaultVariationTargetingOff(), that.getDefaultVariationTargetingOff()) && Objects.equals(this.getDefaultVariationTargetingOn(), that.getDefaultVariationTargetingOn()) && Objects.equals(this.getRolloutRules(), that.getRolloutRules()) && Objects.equals(this.getCreated(), that.getCreated()) && Objects.equals(this.getLastUpdated(), that.getLastUpdated());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getNamespace(), getDefaultVariationTargetingOff(), getDefaultVariationTargetingOn(), getRolloutRules(), getCreated(), getLastUpdated());
    }// endregion hashCode() and equals()

    // region toString() -- generated by BoB the Builder of Beans
    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("id=" + getId())
                .add("namespace=" + getNamespace())
                .add("defaultVariationTargetingOff=" + getDefaultVariationTargetingOff())
                .add("defaultVariationTargetingOn=" + getDefaultVariationTargetingOn())
                .add("rolloutRules=" + getRolloutRules())
                .add("created=" + getCreated())
                .add("lastUpdated=" + getLastUpdated())
                .toString();
    }// endregion toString()

    // region Builder -- generated by BoB the Builder of Beans
    public static RolloutRules.Builder builder() {
        return new RolloutRules.Builder();
    }

    public static RolloutRules.Builder builder(RolloutRules data) {
        return new RolloutRules.Builder(data);
    }

    public static final class Builder {

        private Long id;
        private String namespace;
        private Variation defaultVariationTargetingOff;
        private Variation defaultVariationTargetingOn;
        private List<RolloutRule> rolloutRules = new ArrayList<>();
        private Date created;
        private Date lastUpdated;

        private Builder() {
        }

        private Builder(RolloutRules initialData) {
            this.id = initialData.id;
            this.namespace = initialData.namespace;
            this.defaultVariationTargetingOff = initialData.defaultVariationTargetingOff;
            this.defaultVariationTargetingOn = initialData.defaultVariationTargetingOn;
            this.rolloutRules = new ArrayList<>(initialData.rolloutRules);
            this.created = initialData.created;
            this.lastUpdated = initialData.lastUpdated;
        }

        public Builder setId(@Nullable Long id) {
            this.id = id;
            return this;
        }

        public Builder setNamespace(String namespace) {
            this.namespace = namespace;
            return this;
        }

        public Builder setDefaultVariationTargetingOff(Variation defaultVariationTargetingOff) {
            this.defaultVariationTargetingOff = defaultVariationTargetingOff;
            return this;
        }

        public Builder setDefaultVariationTargetingOn(Variation defaultVariationTargetingOn) {
            this.defaultVariationTargetingOn = defaultVariationTargetingOn;
            return this;
        }

        public Builder setRolloutRules(List<RolloutRule> rolloutRules) {
            this.rolloutRules = rolloutRules;
            return this;
        }

        public Builder addRolloutRule(RolloutRule rolloutRule) {
            this.rolloutRules.add(rolloutRule);
            return this;
        }

        public Builder addRolloutRules(Iterable<RolloutRule> rolloutRules) {
            for (RolloutRule rolloutRule : rolloutRules) {
                addRolloutRule(rolloutRule);
            }
            return this;
        }

        public Builder setCreated(@Nullable Date created) {
            this.created = created;
            return this;
        }

        public Builder setLastUpdated(@Nullable Date lastUpdated) {
            this.lastUpdated = lastUpdated;
            return this;
        }

        public RolloutRules build() {
            return new RolloutRules(id, namespace, defaultVariationTargetingOff, defaultVariationTargetingOn, rolloutRules, created, lastUpdated);
        }
    }// endregion Builder
    // endregion Constructor, getters, setters, equals, hashCode, toString, builder
}
