package org.propagate.common.domain.rollout;

import org.propagate.common.domain.Variation;

import java.util.Objects;
import java.util.StringJoiner;

public class ConditionalDistribution {
    private String condition;
    private Variation variation;

    // region Constructor, getters, setters, equals, hashCode, toString -- generated by BoB the Builder of Beans
    // The code below has been generated by BoB the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke BoB again.
    // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    public ConditionalDistribution(String condition, Variation variation) {
        this.condition = Objects.requireNonNull(condition);
        this.variation = Objects.requireNonNull(variation);
    }

    // region Getters and setters -- generated by BoB the Builder of Beans
    public String getCondition() {
        return condition;
    }

    public void setCondition(String condition) {
        this.condition = Objects.requireNonNull(condition);
    }

    public Variation getVariation() {
        return variation;
    }

    public void setVariation(Variation variation) {
        this.variation = Objects.requireNonNull(variation);
    }// endregion Getters and setters

    // region hashCode() and equals() -- generated by BoB the Builder of Beans
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        ConditionalDistribution that = (ConditionalDistribution) o;

        return Objects.equals(this.getCondition(), that.getCondition()) && Objects.equals(this.getVariation(), that.getVariation());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCondition(), getVariation());
    }// endregion hashCode() and equals()

    // region toString() -- generated by BoB the Builder of Beans
    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("condition=" + getCondition())
                .add("variation=" + getVariation())
                .toString();
    }// endregion toString()
    // endregion Constructor, getters, setters, equals, hashCode, toString
}
